import os
os.system('clear')

print('██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████')
print('The Spook Mansion Mystery                                                                                  day: 1    time: 10:00am')
print('\n')
print('\n')
print('                         ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                         ')
print('                         ▒ Room: Foyer                                                            ▒')
print('                         ▒                                                                        ▒')
print('                         ▒ You find yourself back in the foyer.                                   ▒')
print('                         ▒                                                                        ▒')
print('                         ▒ The grand staircase dominates the room, spiraling up to the second     ▒')
print('                         ▒ floor. You see the suit of armor in the corner, open hand seeming to   ▒')
print('                         ▒ beckon. A grandfather clock stands along the west wall. The time is    ▒')
print('                         ▒ 10:00am. You can hear your steps echo as you move across the parquet   ▒')
print('                         ▒ floor.                                                                 ▒')
print('                         ▒                                                                        ▒')
print('                         ▒                                                                        ▒')
print('                         ▒                                                                        ▒')
print('                         ▒                                                                        ▒')
print('                         ▒                                                                        ▒')
print('                         ▒ To the "North" is a bathroom.                                          ▒')
print('                         ▒ To the "East" is the Parlor.                                           ▒')
print('                         ▒ To the "South" are the doors of the mansion, and front lawns beyond.   ▒')
print('                         ▒ To the "West" is the library.                                          ▒')
print('                         ▒                                                                        ▒')
print('                         ▒                                                                        ▒')
print('                         ▒ What direction would you like to go?                                   ▒')
print('                         ▒                                                                        ▒')
print('                         ▒ Enter your selection, or you may enter "map" or "inventory".           ▒')
print('                         ▒                                                                        ▒')
print('                         ▒                                                                        ▒')
print('                         ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                         ')
print('\n')
print('\n')
print('\n')
print('\n')
print('██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████')
